- lib/index.js
- lib/server.js
- package.json
So I'm still trying to get prerender to be stable without the need of a cronjob (or heroku task) to kill it ...
It has been stable now for ~36 hours, which is a new record (and I got my first night of sleep without pagerduty waking me up for a server that was running hot).  
Maybe someone else can give it a shot to see if their issues are also solved ;-)
--------------
So I reenabled the 'iterations' config that you guys removed from v1 to v2 (but left in the examples).  
It will once again kill the worker thread after the amount of iterations have passed.  
when iterations is 0 the killing of phantomjs is disabled, so maybe you could set the iterations config to 0 by default in server.js instead of 10 (which wasn't doing anything right now) so that this feature is also disabled by …
> another atempt at getting prerender to be stable without a cron killing it

- README.md
You still need to set the region manually if your bucket is located in US West (Northern California).
> Made the region restriction more clear.

- lib/resources/blocked-resources.json
- lib/server.js
- package.json
With my pull request to `phantom`: https://github.com/sgentle/phantomjs-node/pull/229
Passing a variable to `onResourceRequested` can be done now.
See this note in `phantom`:
* onResourceRequested takes a function that executes in the scope of phantom which has access to request.abort(), request.changeUrl(url), and request.setHeader(key,value). The second argument is the callback which can execute in the scope of your code, with access to just the requestData. This function can apply extra arguments which can be passed into the first function e.g.
```
page.onResourceRequested(
function(requestData, request, arg1, arg2) { request.abort(); },
function(requestData) { console.log(requestData.url) },
arg1, arg2
);
```
So I create a json file which include all resources need to be blocked, then …
> Pass blocked request resource list from outside. so the resources need to be blocked is configuarable

- lib/index.js
As proposed in #164 this could be useful for security/obfuscation reasons, without needing to use a firewall setting.
> prerender can now bind to a specific interface using NODE_HOSTNAME

- lib/server.js
fixes Error: Cannot find module 'weak'
see https://github.com/sgentle/phantomjs-node#use-it-in-windows
example:
````javascript
var prerender = require('prerender');
var server = prerender({
dnodeOpts: { weak: false }
});
server.start();
```
> Adds dnodeOpts to disable `weak` option of dnode

- lib/plugins/httpHeaders.js
This pull request resolves #248.
Changed the httpHeaders plugin method from `beforeSend` to `afterPhantomRequest`.
> Added the ability to skip the cache with httpHeaders

- lib/plugins/httpHeaders.js
- package.json
Phantom URL encodes all URLs in it's output, which isn’t entirely unreasonable, and crawlers and browsers seem to understand this, as long as these URLs are described in markup.
Unfortunately this seems to have lead to the assumption in /lib/plugins/httpHeaders.js line 16, that the value in the 'prerender-header’ meta tag is ready to be passed straight out as an HTTP header.
This assumption has lead to, among  other things, ampersands in the query string being encoded as &amp;, and then passed, fully encoded, in to the response headers in situations such as a 301 redirect with the following meta tag being presented in the prerendered document: <meta name="prerender-header" content="http://www.mydomain.com/?query=string&error=maybe" />
The resultant HTTP header is as follows:
`Location: …
> Use HE to decode header values that have already been encoded by Phantom

- README.md
Otherwise weird things happen, and the underscore doesn't render like it should.
> escape the underscore

- README.md
I was wondering and searching for a long time why the S3 upload did not work. Then I found out that it should be enabled in the `server.js`.
> Add information about enabling the plugins

- lib/server.js
Fixes Prerender spawns exponentially growing number of phantomjs processes.
https://github.com/prerender/prerender/issues/243
Please, review if this is the correct way to solve this.
> Fixes prerender/prerender/#243

- lib/server.js
In some cases prerender generates empty page on 304 server respond.
There is clearing of localStorage before disposing phantom's page
in `server._send`, but it is necessary to clear memory cache too in
order to avoid this.
There is a function [clearMemoryCache()](https://github.com/ariya/phantomjs/commit/5768b705a0) in PhantomJS, which allows to clear memory cache.
I found only one different approach to clear memory cache - killing PhantomJS, like it was done in  [prerender-clear-local-storage plugin](/hightail/prerender-clear-local-storage/blob/master/lib/clear-local-storage.js#L108). 
Hope, suggested method using clearMemoryCache() function is more appropriate.
> Clear memory cache on page disposing

- README.md
prerender-go seems to be renamed as goprerender at some point.
> Update the name of goprerender

- README.md
…informative
instead Of <your local url> The "http://localhost:3000" is much more informative.And for nearly half an hour i was thinking it as local app url
> instead Of <your local url> The "http://localhost:3000" is informative

- README.md
GitHub no longer renders headers without a space after the #
> docs(README): make valid markdown

- lib/browsers/chrome.js
In case no Chrome install can be found, chromeChild is never defined, which was making the chrome.kill function crash
> fix chrome.kill for cases when no chromeChild is defined

- lib/browsers/chrome.js
Hi Todd
This pull request fixes an issue where local storage, cookies etc can bleed over into other sessions.
Target.createTarget is expecting the parameter "browserContextId" [[Link toDevtools Protocol Doc]](https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createTarget)
The current code submits this with the name 'browserContext' which is subsequently ignored by Chrome. The fix is to pass the parameter as 'browserContextId'.
This means we don't necessarily pick up the new browserContext we've created, and can reuse session data etc.
I've been using Prerender at reasonable scale, and so I'm pretty confident this fixes that issue. Btw this was using Chrome v69.
Cheers
James
> Fix issue with creating pages in new browser context

- lib/browsers/chrome.js
Hi @thoop , one more PR to send your way. I found that if the requested url redirects, Prerender will wait until the page load timeout (20 sec default) before returning a response. It looks like that's because `chrome.checkIfPageIsDoneLoading` only checks `tab.prerender.domContentEventFired`, which appears to always be false in that case. Adding a check for `tab.prerender.receivedRedirect` appears to fix this issue in my testing so far.
This can be reproduced by running Prerender locally, then hitting http://localhost:3000/https://google.com (which redirects to https://www.google.com ).
> Fix timeouts on redirects

- lib/index.js
We need it in order to set a host to express for security reasons.
I think it could be useful for other purposes of other options ...
> Allow passing options to express

- README.md
to match @thoop's [commit in prerender-node from earlier this year](https://github.com/prerender/prerender-node/commit/dcd5059ed95016ac5e2fd679305e856f698a63c7)
Also, sorta related: https://medium.com/finnovate-io/googlebot-no-longer-picking-up-content-in-prerender-io-pages-ae21d9710459
This change is just me paraphrasing @thoop's revised summary, but adapted to match the sort of step-by-step style that was going on before:
> This middleware intercepts requests to your Node.js website from crawlers, and then makes a call to the (external) Prerender Service to get the static HTML instead of the JavaScript for that page. That HTML is then returned to the crawler.
Making this change because @rachaelshaw and I were about to use prerender on a project, stumbled across this stuff about meta …
> Remove "_escaped_fragment_" stuff from the README

- lib/browsers/chrome.js
Using `node:18-alpine` on kubernetes v1.24.0 with container runtime `containerd`, this stopped working. We have been able to get the code working by moving away from `musl libc` to `glibc` in a `node:18-slim` build.
As a service provider, one of our clients noticed that their prerender server was unable to communicate with chrome, installed using the Dockerfile below:
```dockerfile
FROM node:18-alpine
RUN apk update && \
apk add --no-cache ca-certificates && \
apk add chromium --no-cache && \
npm install prerender@${PRERENDER_VERSION}  && \
npm install prerender-memory-cache@${PRERENDER_MEMORY_VERSION} && \
rm -rf /var/cache/apk/*
WORKDIR /app
COPY package.json package-lock.json index.js .
CMD node index.js
```
in all tests, we were using `node index.js` with the following js file: …
> Update child_process spawn to use shell
